"""Tactic preset library.

Each preset describes a Madgicx-style strategy as:
- default config (thresholds, multipliers, caps) — overridable per-tactic
- rule_specs: how to materialize the tactic into AutomationRule rows
- revert_policy: what (if anything) the daily cron should undo next day

The rule_engine reads `tactic.config` at evaluation time so most overrides
take effect without re-creating rules.
"""

from dataclasses import dataclass, field
from typing import Any, Callable

from app.models.tactic import (
    PRESET_CUSTOM_RULE,
    PRESET_PAUSE_PERMANENT,
    PRESET_PAUSE_TODAY,
    PRESET_REVIVE_AD,
    PRESET_REVIVE_ADSET,
    PRESET_SCALE_WINNING_ADSET,
    PRESET_SCALE_WINNING_CAMPAIGN,
    PRESET_STOP_LOSS_AD,
    PRESET_STOP_LOSS_ADSET,
    PRESET_SUNSETTING,
    PRESET_SURF_ADSET,
    PRESET_SURF_CAMPAIGN,
)

# Revert policies — drives the daily-cron revert phase.
REVERT_NONE = "none"               # Permanent action; never auto-undo
REVERT_NEXT_DAY = "next_day"       # Undo at next daily run (Pause Today, SURF)
REVERT_ON_RECOVERY = "on_recovery" # Re-evaluate next day; tactic decides via REVIVE rule


@dataclass
class RuleSpec:
    """Spec for one AutomationRule generated by a preset.

    `conditions` and `action_params` may include `${...}` template tokens
    referencing keys in `tactic.config` — resolved at rule materialization time.
    """

    name_suffix: str
    entity_level: str  # campaign | ad_set | ad
    action: str        # pause_campaign | pause_adset | pause_ad | enable_* | adjust_budget | send_alert
    conditions: list[dict[str, Any]]
    action_params: dict[str, Any] | None = None


@dataclass
class TacticPreset:
    name: str
    description: str
    default_config: dict[str, Any]
    rule_specs_fn: Callable[[dict[str, Any]], list[RuleSpec]]
    revert_policy: str = REVERT_NONE
    valid_platforms: list[str] = field(default_factory=lambda: ["meta"])


# ---------------------------------------------------------------------------
# Rule-spec builders per preset
# ---------------------------------------------------------------------------

def _stop_loss_ad_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Pause underperforming ads.

    Underperforming = ROAS below floor over `days` AND minimum spend met
    (skips ads that haven't had a fair chance).
    """
    return [
        RuleSpec(
            name_suffix="pause_low_roas",
            entity_level="ad",
            action="pause_ad",
            conditions=[
                {"metric": "roas", "operator": "<", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
        ),
    ]


def _stop_loss_adset_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    return [
        RuleSpec(
            name_suffix="pause_low_roas",
            entity_level="ad_set",
            action="pause_adset",
            conditions=[
                {"metric": "roas", "operator": "<", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
        ),
    ]


def _pause_today_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Pause ads that lost money TODAY (single-day check). Auto-resumes next day.

    Tighter window than stop_loss_ad: looks at 1-day metrics so a single bad day
    can pause without permanently retiring the ad.
    """
    return [
        RuleSpec(
            name_suffix="pause_today",
            entity_level="ad",
            action="pause_ad",
            conditions=[
                {"metric": "roas", "operator": "<", "threshold": cfg["roas_min"], "days": 1},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": 1},
            ],
        ),
    ]


def _pause_permanent_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    return [
        RuleSpec(
            name_suffix="pause_permanent",
            entity_level="ad",
            action="pause_ad",
            conditions=[
                {"metric": "roas", "operator": "<", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
        ),
    ]


def _surf_adset_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Boost budget on winning ad sets. Reverts next day if momentum fades."""
    return [
        RuleSpec(
            name_suffix="surf_boost",
            entity_level="ad_set",
            action="adjust_budget",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
            action_params={
                "budget_multiplier": cfg["budget_multiplier"],
                "max_budget_cap_multiplier": cfg["max_budget_cap_multiplier"],
            },
        ),
    ]


def _surf_campaign_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    return [
        RuleSpec(
            name_suffix="surf_boost",
            entity_level="campaign",
            action="adjust_budget",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
            action_params={
                "budget_multiplier": cfg["budget_multiplier"],
                "max_budget_cap_multiplier": cfg["max_budget_cap_multiplier"],
            },
        ),
    ]


def _revive_ad_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Re-enable paused ads that have shown positive momentum.

    Looks at PAUSED ads; checks if their recent ROAS recovered above floor.
    """
    return [
        RuleSpec(
            name_suffix="revive_recovered",
            entity_level="ad",
            action="enable_ad",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
        ),
    ]


def _revive_adset_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    return [
        RuleSpec(
            name_suffix="revive_recovered",
            entity_level="ad_set",
            action="enable_adset",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
        ),
    ]


def _sunsetting_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Phase 2: Multi-step under-performer wind-down.

    The state machine lives in the rule engine, but each step still needs a
    rule row so logs/UI surface what's happening. Steps are:
      1. Reduce budget by `step1_reduction_pct` (default 25%)
      2. Reduce budget by `step2_reduction_pct` (default 50%, cumulative from original)
      3. Pause permanently

    Step progression is tracked via action_logs queried for the same ad_set.
    See rule_engine.sunsetting_step_for_entity().
    """
    return [
        RuleSpec(
            name_suffix="sunsetting",
            entity_level="ad_set",
            # `adjust_budget` is the entry action; the engine substitutes pause_adset on step 3.
            action="adjust_budget",
            conditions=[
                {"metric": "roas", "operator": "<", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
            action_params={
                "sunsetting": True,
                "step1_reduction_pct": cfg["step1_reduction_pct"],
                "step2_reduction_pct": cfg["step2_reduction_pct"],
            },
        ),
    ]


def _scale_winning_adset_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Phase 2: Sustainable +N%/day budget scaling, capped at max multiplier.

    Differs from SURF: SURF reverts next day; Scale Winning ratchets up gradually
    and keeps the gain (until momentum fades and stop_loss/sunsetting takes over).
    """
    return [
        RuleSpec(
            name_suffix="scale_step",
            entity_level="ad_set",
            action="adjust_budget",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
            action_params={
                "scale_winning": True,
                "daily_step_pct": cfg["daily_step_pct"],
                "max_budget_cap_multiplier": cfg["max_budget_cap_multiplier"],
            },
        ),
    ]


def _custom_rule_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    """Custom-rule preset: a single rule built directly from user config.

    Replaces the legacy /rules UI — users pick entity_level + conditions +
    action, no preset constraint. No revert, no sunsetting, no step machine.
    Fires once per day with the rest of the tactic cohort (17:00 UTC).
    """
    return [
        RuleSpec(
            name_suffix="custom",
            entity_level=cfg.get("entity_level", "ad"),
            action=cfg.get("action", "send_alert"),
            conditions=cfg.get("conditions") or [],
            action_params=cfg.get("action_params") or None,
        ),
    ]


def _scale_winning_campaign_specs(cfg: dict[str, Any]) -> list[RuleSpec]:
    return [
        RuleSpec(
            name_suffix="scale_step",
            entity_level="campaign",
            action="adjust_budget",
            conditions=[
                {"metric": "roas", "operator": ">=", "threshold": cfg["roas_min"], "days": cfg["days"]},
                {"metric": "spend", "operator": ">=", "threshold": cfg["spend_min"], "days": cfg["days"]},
            ],
            action_params={
                "scale_winning": True,
                "daily_step_pct": cfg["daily_step_pct"],
                "max_budget_cap_multiplier": cfg["max_budget_cap_multiplier"],
            },
        ),
    ]


# ---------------------------------------------------------------------------
# Preset registry
# ---------------------------------------------------------------------------

PRESETS: dict[str, TacticPreset] = {
    PRESET_STOP_LOSS_AD: TacticPreset(
        name="Stop Loss — Ad level",
        description="Pause ads with negative momentum after a fair-chance spend window.",
        default_config={"roas_min": 1.5, "spend_min": 100000, "days": 3},
        rule_specs_fn=_stop_loss_ad_specs,
        revert_policy=REVERT_ON_RECOVERY,
    ),
    PRESET_STOP_LOSS_ADSET: TacticPreset(
        name="Stop Loss — Ad Set level",
        description="Pause ad sets with negative momentum after a fair-chance spend window.",
        default_config={"roas_min": 1.5, "spend_min": 300000, "days": 3},
        rule_specs_fn=_stop_loss_adset_specs,
        revert_policy=REVERT_ON_RECOVERY,
    ),
    PRESET_SURF_ADSET: TacticPreset(
        name="Surf — Ad Set level",
        description="Boost ad set budget on positive momentum. Auto-reverts next day.",
        default_config={
            "roas_min": 3.0,
            "spend_min": 200000,
            "days": 3,
            "budget_multiplier": 1.25,
            "max_budget_cap_multiplier": 2.0,
        },
        rule_specs_fn=_surf_adset_specs,
        revert_policy=REVERT_NEXT_DAY,
    ),
    PRESET_SURF_CAMPAIGN: TacticPreset(
        name="Surf — Campaign level",
        description="Boost campaign budget on positive momentum. Auto-reverts next day.",
        default_config={
            "roas_min": 3.0,
            "spend_min": 500000,
            "days": 3,
            "budget_multiplier": 1.25,
            "max_budget_cap_multiplier": 2.0,
        },
        rule_specs_fn=_surf_campaign_specs,
        revert_policy=REVERT_NEXT_DAY,
    ),
    PRESET_REVIVE_AD: TacticPreset(
        name="Revive — Ad level",
        description="Re-enable paused ads that have recovered to profitable ROAS.",
        default_config={"roas_min": 2.0, "spend_min": 50000, "days": 3},
        rule_specs_fn=_revive_ad_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_REVIVE_ADSET: TacticPreset(
        name="Revive — Ad Set level",
        description="Re-enable paused ad sets that have recovered to profitable ROAS.",
        default_config={"roas_min": 2.0, "spend_min": 150000, "days": 3},
        rule_specs_fn=_revive_adset_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_PAUSE_TODAY: TacticPreset(
        name="Pause Losing Ads for Today",
        description="Pause ads that lost money today. Auto-resumes next day.",
        default_config={"roas_min": 1.0, "spend_min": 50000},
        rule_specs_fn=_pause_today_specs,
        revert_policy=REVERT_NEXT_DAY,
    ),
    PRESET_PAUSE_PERMANENT: TacticPreset(
        name="Pause Losing Ads Permanently",
        description="Pause ads with sustained underperformance. Does NOT auto-resume.",
        default_config={"roas_min": 1.0, "spend_min": 200000, "days": 3},
        rule_specs_fn=_pause_permanent_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_SUNSETTING: TacticPreset(
        name="Sunsetting — Ad Set",
        description="Gradually wind down underperforming ad sets: -25% → -50% → pause.",
        default_config={
            "roas_min": 1.5,
            "spend_min": 200000,
            "days": 3,
            "step1_reduction_pct": 0.25,
            "step2_reduction_pct": 0.50,
        },
        rule_specs_fn=_sunsetting_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_SCALE_WINNING_ADSET: TacticPreset(
        name="Scale Winning — Ad Set",
        description="Sustainably grow ad set budget +N%/day on continued winning. Capped.",
        default_config={
            "roas_min": 3.0,
            "spend_min": 200000,
            "days": 3,
            "daily_step_pct": 0.20,
            "max_budget_cap_multiplier": 3.0,
        },
        rule_specs_fn=_scale_winning_adset_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_SCALE_WINNING_CAMPAIGN: TacticPreset(
        name="Scale Winning — Campaign",
        description="Sustainably grow campaign budget +N%/day on continued winning. Capped.",
        default_config={
            "roas_min": 3.0,
            "spend_min": 500000,
            "days": 3,
            "daily_step_pct": 0.20,
            "max_budget_cap_multiplier": 3.0,
        },
        rule_specs_fn=_scale_winning_campaign_specs,
        revert_policy=REVERT_NONE,
    ),
    PRESET_CUSTOM_RULE: TacticPreset(
        name="Custom Rule",
        description="Build your own condition → action. Use when no preset fits.",
        default_config={
            "entity_level": "ad",
            "conditions": [
                {"metric": "roas", "operator": "<", "threshold": 1.0, "days": 7},
            ],
            "action": "send_alert",
            "action_params": None,
        },
        rule_specs_fn=_custom_rule_specs,
        revert_policy=REVERT_NONE,
    ),
}


def get_preset(preset_type: str) -> TacticPreset:
    if preset_type not in PRESETS:
        raise ValueError(f"Unknown preset_type: {preset_type}. Valid: {sorted(PRESETS.keys())}")
    return PRESETS[preset_type]


def list_presets() -> list[dict[str, Any]]:
    """For UI dropdowns. Returns minimal shape — fetch full preset via get_preset."""
    return [
        {
            "preset_type": k,
            "name": p.name,
            "description": p.description,
            "default_config": p.default_config,
            "revert_policy": p.revert_policy,
            "valid_platforms": p.valid_platforms,
        }
        for k, p in PRESETS.items()
    ]
